### ISSUE TITLE
Bundles of articles

### ISSUE THREAD

**Issue by johanflikweert** [MRVDH/picnic-web#15]
Hi,
Did you already implement the bundle of articles? For example that you can retrieve the 'product family':
1 piece eggplant with s1001372, 2 pieces with s1065425, 3 pieces with s1065426 and 4 pieces with s1065427.
Thanks for checking!

**Comment by MRVDH** [comment]
Hi! I haven't maintained this project for over two years, so a lot is probably broken unfortunately, and I also don't see myself updating this anytime soon. I do accept pull requests etc, so if you think it's an easy fix you're free to submit a PR and I'll merge it!

**Comment by johanflikweert** [comment]
No unfortunately it's not an easy fix. Thanks anyways.
